export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const SET_ITEMS = 'SET_ITEMS';
export const FETCH_ITEMS_FAILED = 'FETCH_ITEMS_FAILED';

export const EPIDEMIOLOGY_START = 'EPIDEMIOLOGY_START';
export const EPIDEMIOLOGY_SUCCESS = 'EPIDEMIOLOGY_SUCCESS';
export const EPIDEMIOLOGY_FAIL = 'EPIDEMIOLOGY_FAIL';
export const EPIDEMIOLOGY_INIT = 'EPIDEMIOLOGY_INIT';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';